import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import CompContainer from '@/components/CompContainer';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>ELS Power Sass 01</title>
        <meta name="description" content="ELS Power with Sass Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CompContainer />
    </>
  )
}
